# Generated by Django 2.2.4 on 2020-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_attendsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescriptionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
