# Generated by Django 2.2.4 on 2020-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_attendsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reasonOfDisapproval',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='recimage',
            field=models.ImageField(null=True, upload_to='records/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriptionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
