# Generated by Django 3.0.5 on 2020-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_attendsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='recimage',
            field=models.ImageField(null=True, upload_to='records/', verbose_name=''),
        ),
    ]
