# Generated by Django 2.2.4 on 2020-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_attendsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='recimage',
            field=models.ImageField(null=True, upload_to='records/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriptionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
