# Generated by Django 3.0.7 on 2020-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20201108_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
