# Generated by Django 3.0.5 on 2020-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20201107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
